/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg126355;

import it.unicam.cs.mpgc.rpg126355.Controller.BasicController;
import it.unicam.cs.mpgc.rpg126355.Controller.Controller;
import it.unicam.cs.mpgc.rpg126355.Model.*;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import it.unicam.cs.mpgc.rpg126355.View.MainView;

/**
 * Classe principale dell'applicazione
 * Inizializza i controller e avvia la GUI con la vista principale
 */
public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {

        Controller<Enemy> enemyController = new BasicController<>(Enemy.class);
        Controller<Boss> bossController = new BasicController<>(Boss.class);
        Controller<Hero> heroController = new BasicController<>(Hero.class);
        Controller<Weapon> weaponController = new BasicController<>(Weapon.class);

        FXMLLoader loader = new FXMLLoader(getClass().getResource("/MainView.fxml"));

        Parent root = loader.load();

        MainView mainView = loader.getController();

        mainView.setControllers(enemyController, bossController, heroController, weaponController);

        Scene scene = new Scene(root, 900, 600);
        scene.getStylesheets().add(getClass().getResource("/rpg-theme.css").toExternalForm());

        primaryStage.setTitle("⚔ RPG – Realm of Heroes ⚔");
        primaryStage.setMinWidth(800);
        primaryStage.setMinHeight(550);
        primaryStage.setScene(scene);

        primaryStage.setFullScreenExitHint("Per uscire dalla modalità FULLSCREEN premere ESC");
        primaryStage.setFullScreen(true);

        primaryStage.show();
    }

    /**
     * Metodo main che lancia l'applicazione JavaFX.
     */
    public static void main(String[] args) {
        launch();
    }
}
